// Generated by scripts/generate-reference-data.ts. Do not edit by hand.
export const referenceRows = {
  "curated_interactions": [
    {
      "salt_a": "aspirin",
      "salt_b": "warfarin",
      "severity": "major",
      "mechanism_en": "Additive anticoagulant/antiplatelet effect — increased bleeding risk",
      "explanation_en": "{a} and {b} both make bleeding easier. Taken together they can cause serious bleeding.",
      "explanation_hi": "{a} और {b} दोनों खून को पतला करते हैं। साथ लेने से गंभीर ब्लीडिंग (खून बहने) का खतरा है।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "ibuprofen",
      "salt_b": "warfarin",
      "severity": "major",
      "mechanism_en": "NSAID plus anticoagulant — GI bleeding risk",
      "explanation_en": "{a} is a painkiller that can cause stomach bleeding, and {b} thins the blood. Together the bleeding risk is high.",
      "explanation_hi": "{a} एक दर्द निवारक है जो पेट में ब्लीडिंग कर सकती है, और {b} खून पतला करती है। साथ में खतरा बढ़ जाता है।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "aspirin",
      "salt_b": "clopidogrel",
      "severity": "moderate",
      "mechanism_en": "Dual antiplatelet — bleeding risk unless deliberately prescribed",
      "explanation_en": "{a} and {b} both reduce clotting. Sometimes doctors prescribe them together on purpose, but confirm this is intended.",
      "explanation_hi": "{a} और {b} दोनों खून जमने से रोकते हैं। कभी-कभी डॉक्टर इन्हें जानबूझकर साथ देते हैं, पर एक बार पक्का कर लें।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "amlodipine",
      "salt_b": "simvastatin",
      "severity": "moderate",
      "mechanism_en": "CYP3A4 interaction — simvastatin dose should not exceed 20 mg",
      "explanation_en": "{a} can raise the level of {b} in the blood. The simvastatin dose usually should not be more than 20 mg with it.",
      "explanation_hi": "{a}, {b} का स्तर खून में बढ़ा सकती है। साथ में सिमवास्टेटिन की खुराक आमतौर पर 20 mg से ज़्यादा नहीं होनी चाहिए।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "spironolactone",
      "salt_b": "telmisartan",
      "severity": "moderate",
      "mechanism_en": "ARB plus potassium-sparing diuretic — hyperkalemia risk",
      "explanation_en": "{a} and {b} can both raise potassium in the blood. Too much potassium can affect the heart.",
      "explanation_hi": "{a} और {b} दोनों खून में पोटैशियम बढ़ा सकती हैं। ज़्यादा पोटैशियम दिल पर असर डाल सकता है।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "potassium chloride",
      "salt_b": "telmisartan",
      "severity": "moderate",
      "mechanism_en": "ARB plus potassium supplement — hyperkalemia risk",
      "explanation_en": "{a} adds potassium and {b} keeps potassium in the body. Together potassium can get too high.",
      "explanation_hi": "{a} पोटैशियम बढ़ाती है और {b} उसे शरीर में रोकती है। साथ में पोटैशियम बहुत ज़्यादा हो सकता है।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "isosorbide dinitrate",
      "salt_b": "sildenafil",
      "severity": "major",
      "mechanism_en": "Nitrate plus PDE5 inhibitor — severe hypotension",
      "explanation_en": "{a} and {b} together can drop blood pressure dangerously low. This combination should be avoided.",
      "explanation_hi": "{a} और {b} साथ लेने से ब्लड प्रेशर खतरनाक रूप से गिर सकता है। इन्हें साथ नहीं लेना चाहिए।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "sertraline",
      "salt_b": "tramadol",
      "severity": "major",
      "mechanism_en": "Serotonin syndrome risk",
      "explanation_en": "{a} and {b} together can raise serotonin too much, which can be dangerous (serotonin syndrome).",
      "explanation_hi": "{a} और {b} साथ में सेरोटोनिन बहुत बढ़ा सकती हैं, जो खतरनाक हो सकता है।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "atorvastatin",
      "salt_b": "clarithromycin",
      "severity": "moderate",
      "mechanism_en": "CYP3A4 inhibition — myopathy risk",
      "explanation_en": "{b} can raise the level of {a}, which may cause muscle pain or damage.",
      "explanation_hi": "{b}, {a} का स्तर बढ़ा सकती है, जिससे मांसपेशियों में दर्द या नुकसान हो सकता है।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    },
    {
      "salt_a": "metoprolol",
      "salt_b": "verapamil",
      "severity": "moderate",
      "mechanism_en": "Additive cardiac depression — bradycardia risk",
      "explanation_en": "{a} and {b} together can slow the heart too much. Your pulse and blood pressure need watching.",
      "explanation_hi": "{a} और {b} साथ में दिल की धड़कन बहुत धीमी कर सकती हैं। नब्ज़ और ब्लड प्रेशर पर नज़र ज़रूरी है।",
      "action_en": "Discuss with your doctor before the next dose.",
      "action_hi": "अगली खुराक से पहले डॉक्टर से बात करें।"
    }
  ],
  "janaushadhi_products": [
    {
      "product_code": "JA001",
      "generic_name": "telmisartan",
      "strength_value": "40",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "10.00"
    },
    {
      "product_code": "JA002",
      "generic_name": "amlodipine",
      "strength_value": "5",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "3.40"
    },
    {
      "product_code": "JA003",
      "generic_name": "metformin",
      "strength_value": "500",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "5.10"
    },
    {
      "product_code": "JA004",
      "generic_name": "aspirin",
      "strength_value": "75",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "14",
      "mrp_inr": "3.90"
    },
    {
      "product_code": "JA005",
      "generic_name": "atorvastatin",
      "strength_value": "10",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "13.00"
    },
    {
      "product_code": "JA006",
      "generic_name": "pantoprazole",
      "strength_value": "40",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "8.50"
    },
    {
      "product_code": "JA007",
      "generic_name": "paracetamol",
      "strength_value": "650",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "6.60"
    },
    {
      "product_code": "JA008",
      "generic_name": "metoprolol",
      "strength_value": "25",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "8.00"
    },
    {
      "product_code": "JA009",
      "generic_name": "losartan",
      "strength_value": "50",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "9.00"
    },
    {
      "product_code": "JA010",
      "generic_name": "glimepiride",
      "strength_value": "1",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "4.00"
    },
    {
      "product_code": "JA011",
      "generic_name": "telmisartan",
      "strength_value": "80",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "17.00"
    },
    {
      "product_code": "JA012",
      "generic_name": "metformin",
      "strength_value": "1000",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "9.80"
    },
    {
      "product_code": "JA013",
      "generic_name": "amlodipine",
      "strength_value": "10",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "5.20"
    },
    {
      "product_code": "JA014",
      "generic_name": "clopidogrel",
      "strength_value": "75",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "15.00"
    },
    {
      "product_code": "JA015",
      "generic_name": "glimepiride",
      "strength_value": "2",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "6.00"
    },
    {
      "product_code": "JA016",
      "generic_name": "rosuvastatin",
      "strength_value": "10",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "16.00"
    },
    {
      "product_code": "JA017",
      "generic_name": "ramipril",
      "strength_value": "5",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "9.50"
    },
    {
      "product_code": "JA018",
      "generic_name": "cetirizine",
      "strength_value": "10",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "3.00"
    },
    {
      "product_code": "JA019",
      "generic_name": "omeprazole",
      "strength_value": "20",
      "strength_unit": "mg",
      "form": "capsule",
      "pack_size": "10",
      "mrp_inr": "7.00"
    },
    {
      "product_code": "JA020",
      "generic_name": "paracetamol",
      "strength_value": "500",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "4.50"
    }
  ],
  "brand_prices": [
    {
      "brand_name": "Telma 40",
      "manufacturer": "Glenmark",
      "generic_name": "telmisartan",
      "strength_value": "40",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "30",
      "mrp_inr": "234.00"
    },
    {
      "brand_name": "Amlong 5",
      "manufacturer": "Micro Labs",
      "generic_name": "amlodipine",
      "strength_value": "5",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "30",
      "mrp_inr": "106.00"
    },
    {
      "brand_name": "Glycomet 500",
      "manufacturer": "USV",
      "generic_name": "metformin",
      "strength_value": "500",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "20",
      "mrp_inr": "35.00"
    },
    {
      "brand_name": "Ecosprin 75",
      "manufacturer": "USV",
      "generic_name": "aspirin",
      "strength_value": "75",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "14",
      "mrp_inr": "9.30"
    },
    {
      "brand_name": "Warf 5",
      "manufacturer": "Cipla",
      "generic_name": "warfarin",
      "strength_value": "5",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "30",
      "mrp_inr": "128.00"
    },
    {
      "brand_name": "Dolo 650",
      "manufacturer": "Micro Labs",
      "generic_name": "paracetamol",
      "strength_value": "650",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "15",
      "mrp_inr": "33.60"
    },
    {
      "brand_name": "Pan 40",
      "manufacturer": "Alkem",
      "generic_name": "pantoprazole",
      "strength_value": "40",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "15",
      "mrp_inr": "155.00"
    },
    {
      "brand_name": "Atorva 10",
      "manufacturer": "Zydus",
      "generic_name": "atorvastatin",
      "strength_value": "10",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "30",
      "mrp_inr": "95.00"
    },
    {
      "brand_name": "Clopilet 75",
      "manufacturer": "Sun Pharma",
      "generic_name": "clopidogrel",
      "strength_value": "75",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "10",
      "mrp_inr": "55.00"
    },
    {
      "brand_name": "Losar 50",
      "manufacturer": "Unichem",
      "generic_name": "losartan",
      "strength_value": "50",
      "strength_unit": "mg",
      "form": "tablet",
      "pack_size": "15",
      "mrp_inr": "72.00"
    }
  ],
  "highrisk_meds": [
    {
      "salt": "warfarin",
      "reason_en": "Narrow therapeutic index — bleeding risk",
      "reason_hi": "खून पतला करने की दवा — विशेष सावधानी ज़रूरी",
      "special_check": "none"
    },
    {
      "salt": "insulin",
      "reason_en": "Hypoglycemia risk — dosing errors dangerous",
      "reason_hi": "शुगर बहुत कम होने का खतरा",
      "special_check": "none"
    },
    {
      "salt": "methotrexate",
      "reason_en": "Usually WEEKLY dosing — daily intake is dangerous",
      "reason_hi": "आमतौर पर हफ़्ते में एक बार — रोज़ लेना खतरनाक",
      "special_check": "weekly_check"
    },
    {
      "salt": "digoxin",
      "reason_en": "Narrow therapeutic index",
      "reason_hi": "दिल की दवा — विशेष सावधानी ज़रूरी",
      "special_check": "none"
    },
    {
      "salt": "lithium",
      "reason_en": "Narrow therapeutic index — levels must be monitored",
      "reason_hi": "विशेष निगरानी ज़रूरी",
      "special_check": "none"
    },
    {
      "salt": "amiodarone",
      "reason_en": "Multiple serious interactions",
      "reason_hi": "कई दवाओं के साथ गंभीर प्रतिक्रिया",
      "special_check": "none"
    },
    {
      "salt": "phenytoin",
      "reason_en": "Narrow therapeutic index",
      "reason_hi": "विशेष सावधानी ज़रूरी",
      "special_check": "none"
    },
    {
      "salt": "carbamazepine",
      "reason_en": "Many interactions via liver enzymes",
      "reason_hi": "कई दवाओं पर असर डालती है",
      "special_check": "none"
    },
    {
      "salt": "glimepiride",
      "reason_en": "Hypoglycemia risk in elderly",
      "reason_hi": "बुज़ुर्गों में शुगर कम होने का खतरा",
      "special_check": "none"
    },
    {
      "salt": "glibenclamide",
      "reason_en": "Hypoglycemia risk in elderly",
      "reason_hi": "बुज़ुर्गों में शुगर कम होने का खतरा",
      "special_check": "none"
    },
    {
      "salt": "tramadol",
      "reason_en": "Serotonin syndrome and dependence risk",
      "reason_hi": "विशेष सावधानी ज़रूरी",
      "special_check": "none"
    }
  ]
} as const;
