import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import Papa from "papaparse";

const root = process.cwd();
const names = ["curated_interactions", "janaushadhi_products", "brand_prices", "highrisk_meds"] as const;

async function main() {
  const tables = await Promise.all(
    names.map(async (name) => {
      const csv = await readFile(join(root, "data", `${name}.csv`), "utf8");
      const parsed = Papa.parse<Record<string, string>>(csv, { header: true, skipEmptyLines: true });
      if (parsed.errors.length > 0) throw new Error(`${name}: ${parsed.errors.map((error) => error.message).join("; ")}`);
      return [name, parsed.data] as const;
    }),
  );
  const output = `// Generated by scripts/generate-reference-data.ts. Do not edit by hand.\nexport const referenceRows = ${JSON.stringify(Object.fromEntries(tables), null, 2)} as const;\n`;
  const target = join(root, "src", "lib", "reference-data.generated.ts");
  await mkdir(dirname(target), { recursive: true });
  await writeFile(target, output, "utf8");
}

void main();
